### ISSUE TITLE
Erro ao tentar verificar cep.

### ISSUE THREAD

**Issue by edufpin** [jpdroid/flutter-correios#1]
Boa noite, estava utilizando normalmente o pacote, porém sem realizar nenhuma alteração no código ele deixou de funcionar, a mensagem que recebo é a seguinte:

I/flutter ( 7864): Receiver: null
I/flutter ( 7864): Tried calling: [] (area_km2)

Função:

  void _verificarCEP() async {
    ResultadoCEP resultado = await fc.consultarCEP(cep: _cepController.text);
    if (resultado != null) {
      _adressController.text = resultado.logradouro;
      _districController.text = resultado.bairro;
      _cityController.text = resultado.cidade;
      _stateController.text = resultado.estado;
    }
  }

Obrigado por ter feito o pacote e pela possível ajuda!

**Comment by jpdroid** [comment]
Vou verificar o que aconteceu, provavelmente foi o site dos correios.

Em seg, 15 de jul de 2019 às 18:41, edufpin <notifications@github.com>
escreveu:

**Comment by jpdroid** [comment]
Qual CEP você está usando pra testar?
Tente com outros CEPs.

Em qua, 17 de jul de 2019 às 11:03, João Paulo de Oliveira <
jpdroid.jpo@gmail.com> escreveu:

**Comment by edufpin** [comment]
Boa noite João,

Acho que realmente foi algo no correios, voltou a funcionar sem nenhuma alteração.

**Comment by edufpin** [comment]
O problema voltou a acontecer, modifiquei o seu pacote para resolver o problema, acredito que o erro seja ao tentar decodificar o json onde o valor km2 do estado é nulo.
